name: Keep FastAPI Alive

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minute

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests

      - name: Run keep_alive.py
        run: python keep_alive.py
